### ISSUE TITLE
Add some kind of 'labs' page

### ISSUE THREAD

**Issue by workmanw** [sproutcore/website#4]
I'm not sure 'labs' would be the best name for it. But I think it would be really great if we had a page that listed, and maybe showed screenshots, of 3rd party SproutCore frameworks that were out there. A few examples might be:

Sai 
SproutCore-UI
jslewis Table
Endash Table

**Comment by geoffreyd** [comment]
This is a great idea ... easier accessibility for finding add-on frameworks would be great

+1

**Comment by tim-evans** [comment]
+1

**Comment by geojeff** [comment]
We could have a 'sample apps' page too, as discussed in the sprint, and for which several apps were listed on the sprint wiki page: https://github.com/sproutcore/sproutcore/wiki/1.8-Release-Sprint, under the section titled Idea: New Guides Page for Sample Apps.

Maybe labs would be a general (top-level) section? ... so that it would be something like: 

labs/add-ons/views (views, widgets, whatever they might be called)
labs/add-ons/frameworks (could be categorized as graphics, tables, etc., but that takes management)
labs/sample-apps

Are there other projects that have a labs section? To some extent it has the connotation of an area where active development of new things is happening, vs. a place where add-ons that will likely forever remain optional live. I've also seen the name 'collective' used, as in a shared space for contributions that are not officially part of the project. Something like that could be better than 'labs', perhaps even 'contributions'. The name 'labs' works well for handling the case where a view or a framework lives first, perhaps for a significant period, in labs, before maturing to a point, or before it is just needed, to become officially adopted, then it would be moved out of labs into SC. Perhaps the term 'lab' could be restricted to items that have been earmarked or proposed as SC replacement or addition items, so it could be contributions/add-ons/views, contributions/add-ons/frameworks, contributions/lab/views, contributions/lab/frameworks, etc.

I use a little wrapper framework around d3 called d3sc that could go in also. Plus there is the one for flot, etc.  

Also, would this system fit as part of the website or as part of the guides pages?

**Comment by geojeff** [comment]
Whether it is a website or a guides component, the actual layout and management could be done on github, where maybe there are some built-in tools in gh-pages that might help put a face on the actual code entries in the repo hierarchy.

**Comment by publickeating** [comment]
I think our website is actually too unmanageable to do this very well, because content changes really need to be done in concert with a designer and the site has a lot of code to maintain.  We should probably go to a much simpler design at some point that we can maintain without a web-team...

But anyway, I agree with doing this too.  Since we have apps, demos and frameworks all over the place, I've been thinking we need to build a single app that includes test controls, demos, experimental and supporting frameworks all together.  Something similar to the existing Test Controls app, but with additional super-sections like: 
- Views & Controls:  SC.ButtonView, SC.RadioView, etc.
- Demos: family_tree, signup, etc.
- Labs: scroll_view, split_view, etc.
- Popular Additions: endash table, jslewis table, upload view, etc.

The app and all the code could be a sub-project of sproutcore/ and most importantly, have a live version always available using gh-pages like @geojeff mentions.  I think the availability of a live sample of controls and cool demos is absolutely critical.  I've spoken with many devs and the reason they tried SproutCore first wasn't because they understood the data store or statecharts or the run loop, but because they were impressed by the controls and demos.

You don't have to agree with the headings I used up there, but what do you think of this approach?

**Comment by workmanw** [comment]
+1 to the idea of being in a gh-pages making it easy push to.

Sounds like we all agree that this is a good idea. Let's start by compiling a list of third party frameworks that would could display on the "labs" page. I'll assume responsibility for this one. The upload framework is another good example, please keep them coming. I'm going to post something on the SproutCore groups asking for more frameworks that could be listed and I'll take it from there.

@geojeff At the company I work for, Seapine Software, we have a "labs page". We typically have coops/interns that work on isolated projects during their employment with us. Typically we host that on our "labs page". The idea is that the labs site contains content that is related to us, but that we don't officially support. ( http://labs.seapine.com ). SproutCore's situation here is slightly different and the name 'labs' doesn't really seem to fit. But the idea seems similar enough.

**Comment by publickeating** [comment]
I would still like to make the "Showcase" app, which would give a view to each SproutCore control, each demo, each experimental framework and each 3rd-party framework.

Also, I realize that it could become a tab off of the website like Guides, Docs and Blogs are.  Okay if I take a stab at this?

**Comment by geojeff** [comment]
Sounds great. Having the code as easy-to-grab separate views would be handy.

**Comment by workmanw** [comment]
@publickeating Yea, that sounds great too me. Have at it :)

**Comment by dcporter** [comment]
Closing this as stale. Tyler got Showcase together; meanwhile, we're approaching the question of 3rd-party frameworks separately (and the circumstances have changed).
